### PR TITLE
Dashboard: Fix sorting of routes by name (title).

### LINKED ISSUE #164: Improve route sorting
Pretty small issue but I'll flag it nonetheless.

Currently the routes are sorted like 1, 10, 11, ... 19, 1AX, 1BX, 2, 20, 21, etc. Ideally it would be sorted like 1, 1AX, 1BX, 2, 3, ... 9, 10, 11, ... 20, 21, etc. That is, we should sort by route number, not lexically.

Screenshot 2019-07-10 at 8 38 57 PM

### PR DESCRIPTION
**Pull request by exxonvaldez**
Fixes #164.

## Proposed changes

When sorting by route name (internally `title`), use the natural order of the routes array, which comes from Nextbus. It is the simplest way to get a "good" ordering for the routes without having to implement a hybrid numeric/lexical sort.

## Screenshot

Screen Shot 2019-10-01 at 9 30 28 PM

## Link to demo, if any

n/a

### CODE REVIEW

File: frontend/src/components/RouteTable.jsx [hunk 1]
```diff
@@ -50,7 +50,31 @@ function desc(a, b, orderBy) {
...
+ * 
+ * Sorting by title is a special case because the original order of the routes array is
+ * better than sorting route title alphabetically.  For example, 1 should be followed by
+ * 1AX rather than 10 and 12.
+ *  
+ * @param {Array} array      Array to sort
+ * @param {Function} cmp     Comparator to use
+ * @param {String} sortOrder Either 'desc' or 'asc'
+ * @param {String} orderBy   Column to sort by
+ */
```
Comment (akgupta89) [inline frontend/src/components/RouteTable.jsx]: It's usually good to include a `@return` definition here

Comment (exxonvaldez) [reply frontend/src/components/RouteTable.jsx]: Ok, @returns added.
